[package]
name = "rustls"
version = "0.15.1"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"
categories = ["network-programming", "cryptography"]

[dependencies]
untrusted = "0.6.2"
base64 = "0.10"
log = { version = "0.4.0", optional = true }
ring = "0.14"
webpki = "0.19"
sct = "0.5"

[features]
default = ["logging"]
logging = ["log"]
dangerous_configuration = []
quic = []

[dev-dependencies]
log = "0.4"
env_logger = "0.6"
#mio = "0.6"
docopt = "1.0"
serde = "1.0"
serde_derive = "1.0"
webpki-roots = "0.16"
ct-logs = "0.5"
regex = "1.0"
vecio = "0.1"
tempfile = "3.0"

#[[example]]
#name = "bogo_shim"
#path = "examples/internal/bogo_shim.rs"
#required-features = ["dangerous_configuration", "quic"]
#
#[[example]]
#name = "trytls_shim"
#path = "examples/internal/trytls_shim.rs"
#
#[[example]]
#name = "bench"
#path = "examples/internal/bench.rs"
#
#[[example]]
#name = "tlsclient"
#path = "examples/tlsclient.rs"
#
#[[example]]
#name = "tlsserver"
#path = "examples/tlsserver.rs"
#
#[[example]]
#name = "simpleclient"
#path = "examples/simpleclient.rs"
#
#[[example]]
#name = "simple_0rtt_client"
#path = "examples/simple_0rtt_client.rs"
#required-features = ["logging"]
